### ISSUE TITLE
fatal error: Python.h: No such file or directory  

### ISSUE THREAD

**Issue by hichem-abdellali** [alexander-vakhitov/lbdmod#1]
Hi,

After installing all the requirement, I run `cmake .`  successfully. but, when I execute `make`  it built until 48% and shows an error 

```
[ 48%] Building CXX object CMakeFiles/pylbd.dir/src/pyboost_cv2_converter.cpp.o
In file included from /mnt/data2/user/lld-public/lbdmod/src/pyboost_cv2_converter.cpp:10:0:
/mnt/data2/user/lld-public/lbdmod/./include/pyboostcvconverter/pyboostcvconverter.hpp:14:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
```

Could you know why this is happening?

Thanks

**Comment by alexandervakhitov** [comment]
Please see the CMakeLists.txt, lines 21-31. You should set all the variables to actual paths on your system. In particular, the variable PYTHON_INCLUDE_DIR should point to the folder which contains Python.h. I mentioned that under the no. 2 in the Readme.md file.

**Comment by yosungho** [comment]
For those who got the same issue, I fixed it by referring to CMakeLists.txt in this Github (https://github.com/Algomorph/pyboostcvconverter) and this site (https://stackoverflow.com/questions/47237098/opencv-cmake-could-not-find-pythonlibs-found-unsuitable-version-ubuntu)
